- src/fdk_rdf_parser/fdk_rdf_parser.py
- src/fdk_rdf_parser/parse_functions/dataservice.py
- src/fdk_rdf_parser/parse_functions/dataset.py
- src/fdk_rdf_parser/parse_functions/dcat_resource.py
- src/fdk_rdf_parser/parse_functions/publisher.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/utils.py
- tests/test_data_service.py
- tests/test_dcat_resource.py
- tests/test_publisher.py
Henter data for publisher fra org-cat for datatjenester, burde hjelpe på filter-problemet i portal
> feat: publisher from catalog when missing from resource

- src/fdk_rdf_parser/rdf_utils/utils.py
- tests/test_dataset.py
Tar seg av problemet jeg nevnte ang. spatial, legger nå ikke til den genererte referansen til blanke noder som feltverdi
> fix: blank node references not added as object value

- pyproject.toml
- src/fdk_rdf_parser/fdk_rdf_parser.py
- tests/test_data_service.py
Fikk svi litt for å ikke vente på review
> fix: actually extend data services with reference data

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/organizations/utils.py
- tests/test_organization.py
Med dette så burde dsop-apiene få publisher i portal
> chore: match fdk org uri as publisher

- src/fdk_rdf_parser/fdk_rdf_parser.py
- tests/test_info_model.py
Knotet litt vel mye med dette på fredag, men var jo ikke nødvendig å alltid bruke turtle :+1:
> fix: handle escaped char

- pyproject.toml
- src/fdk_rdf_parser/parse_functions/cost.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/utils.py
- tests/test_public_service.py
Må håndtere verdi 0. Som Literal blir 0 tolket som None. Men for cost vil man at verdien 0 skal tolkes som en reel verdi.
> fix(public-service): parse cost as number

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/test-pypi.yml
- .github/workflows/tests.yml
- README.md
- mypy.ini
- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/info_model.py
- src/fdk_rdf_parser/parse_functions/concept.py
- src/fdk_rdf_parser/parse_functions/info_model.py
- src/fdk_rdf_parser/parse_functions/rule.py
- tests/test_info_model.py
- tests/test_public_service.py
Vi hadde visst 3 bugs der vi brukte feil namespace, det klarte ny rdflib å plukke opp :+1:
> bump rdflib

- pyproject.toml
- src/fdk_rdf_parser/classes/__init__.py
- src/fdk_rdf_parser/classes/conforms_to.py
- src/fdk_rdf_parser/classes/dataset.py
- src/fdk_rdf_parser/classes/distribution.py
- src/fdk_rdf_parser/parse_functions/__init__.py
- src/fdk_rdf_parser/parse_functions/conforms_to.py
- src/fdk_rdf_parser/parse_functions/dataset.py
- src/fdk_rdf_parser/parse_functions/distribution.py
- tests/test_dataset.py
- tests/test_distribution.py
> fix: deserialize dataset&distribution conformsTo as dct:Standard

- src/fdk_rdf_parser/classes/info_model.py
- tests/test_info_model.py
Closes Informasjonsforvaltning/fdk-issue-tracker#405
> fix: include subjects related to code elements

- pyproject.toml
- src/fdk_rdf_parser/parse_functions/references.py
- tests/test_references.py
Part of Informasjonsforvaltning/fdk-portal#1050
> feat: parse reference labels

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/parse_functions/media_type.py
- tests/test_dataset.py
resolve https://github.com/Informasjonsforvaltning/fdk-fulltext-search/issues/168
> fix: rm error-log for missing value when parsing single media type

- poetry.lock
- src/fdk_rdf_parser/reference_data/reference_data.py
- tests/conftest.py
- tests/json_data/rightsstatement.json
> get access rights from new reference-data

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/parse_functions/publisher.py
- tests/test_info_model.py
- tests/test_publisher.py
resolves https://github.com/Informasjonsforvaltning/fdk-portal/issues/1130
> feat: set publisher name from prefLabel when missing

- pyproject.toml
- src/fdk_rdf_parser/classes/format.py
- src/fdk_rdf_parser/parse_functions/format.py
- tests/test_info_model.py
> fix: change seeAlso for hasFormat in infomodels from list to string

- .github/workflows/constraints.txt
- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/__init__.py
- src/fdk_rdf_parser/classes/businessEvent.py
- src/fdk_rdf_parser/classes/business_event.py
- src/fdk_rdf_parser/classes/event.py
- src/fdk_rdf_parser/classes/lifeEvent.py
- src/fdk_rdf_parser/classes/life_event.py
- src/fdk_rdf_parser/fdk_rdf_parser.py
- src/fdk_rdf_parser/parse_functions/event.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/ns.py
- tests/test_event.py
> parse cv:Event

- .github/workflows/safety.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/__init__.py
- src/fdk_rdf_parser/classes/dataset.py
- src/fdk_rdf_parser/fdk_rdf_parser.py
- src/fdk_rdf_parser/parse_functions/__init__.py
- src/fdk_rdf_parser/parse_functions/dataset.py
- tests/test_dataset_series.py
resolve #153 
Mtp safety:
Jeg tar en prat med Hans Olav om beste måten å kjøre den på, blir feil å stoppe alt pga feil fra den. Regner uansett med at vi oppretter et eget issue, og egen pr
> parse dataset series

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/dataset.py
- src/fdk_rdf_parser/parse_functions/dataset.py
- tests/test_dataset_series.py
> fix: add dcat:prev to datasets

- .github/workflows/tests.yml
Related to https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/632
> chore: setup matrix for tests workflow

- src/fdk_rdf_parser/classes/cpsvno_service.py
- src/fdk_rdf_parser/classes/public_service.py
- src/fdk_rdf_parser/parse_functions/cpsvno_service.py
- src/fdk_rdf_parser/reference_data/extend_cpsvno_service.py
- src/fdk_rdf_parser/reference_data/reference_data.py
- tests/conftest.py
- tests/json_data/statuses.json
- tests/test_public_service.py
> feat: update parse of services to include dct:type

- poetry.lock
- src/fdk_rdf_parser/classes/output.py
- src/fdk_rdf_parser/parse_functions/output.py
- src/fdk_rdf_parser/reference_data/extend_cpsvno_service.py
- tests/test_public_service.py
closes [oppdater parse av tjenester til å hente ut språk for tjenesteresultat#179](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/179)
> feat: parse dct:language in service output

- pyproject.toml
- src/fdk_rdf_parser/classes/cpsvno_service.py
- src/fdk_rdf_parser/classes/public_service.py
- src/fdk_rdf_parser/parse_functions/cpsvno_service.py
- tests/test_public_service.py
> chore: update parse to get related terms

- src/fdk_rdf_parser/classes/cpsvno_service.py
- src/fdk_rdf_parser/classes/public_service.py
- src/fdk_rdf_parser/parse_functions/cpsvno_service.py
- tests/test_public_service.py
> chore: update parse to get homepage

- src/fdk_rdf_parser/classes/cpsvno_service.py
- src/fdk_rdf_parser/parse_functions/cpsvno_service.py
- src/fdk_rdf_parser/reference_data/extend_cpsvno_service.py
- src/fdk_rdf_parser/reference_data/reference_data.py
- src/fdk_rdf_parser/reference_data/utils.py
- tests/json_data/eudatatheme.json
- tests/json_data/los.json
- tests/test_public_service.py
- tests/testdata.py
> feat: include thematic areas in Service

- src/fdk_rdf_parser/classes/rule.py
- src/fdk_rdf_parser/parse_functions/cpsvno_service.py
- src/fdk_rdf_parser/parse_functions/legal_resource.py
- src/fdk_rdf_parser/parse_functions/rule.py
- tests/test_public_service.py
> feat: include 'implements' in Rule

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/contactpoint.py
- src/fdk_rdf_parser/parse_functions/contactpoint.py
- tests/test_public_service.py
> fix: add missing type field for cv:ContactPoint

- src/fdk_rdf_parser/classes/channel.py
- src/fdk_rdf_parser/parse_functions/channel.py
- tests/test_public_service.py
hasChannel manglet telefonnummer:-)
> Feat/ha/170/update hasChannel with telephone number

- src/fdk_rdf_parser/classes/organization.py
- src/fdk_rdf_parser/parse_functions/organization.py
- src/fdk_rdf_parser/reference_data/extend_cpsvno_service.py
- src/fdk_rdf_parser/reference_data/reference_data.py
- tests/conftest.py
- tests/json_data/publishertypes.json
- tests/test_extend_public_service_with_reference_data.py
- tests/test_organization.py
- tests/test_public_service.py
- tests/testdata.py
> feat: fixes #212 update orgType

- src/fdk_rdf_parser/parse_functions/evidence.py
- tests/test_public_service.py
> feat: collect Evidence also from Channel.hasInput

- src/fdk_rdf_parser/classes/__init__.py
- src/fdk_rdf_parser/classes/dataset.py
- src/fdk_rdf_parser/parse_functions/dataset.py
- tests/test_dataset_series.py
> feat: add info on series a dataset is part of

- src/fdk_rdf_parser/classes/concept.py
- src/fdk_rdf_parser/parse_functions/concept.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/ns.py
- tests/test_concept.py
> feat: parse concept status

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/classes/concept.py
- src/fdk_rdf_parser/parse_functions/concept.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/ns.py
- tests/test_concept.py
resolves https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/258
> feat(concept): add exactMatch & closeMatch

- pyproject.toml
- src/fdk_rdf_parser/classes/cpsvno_service.py
- src/fdk_rdf_parser/classes/public_service.py
- src/fdk_rdf_parser/fdk_rdf_parser.py
- src/fdk_rdf_parser/parse_functions/__init__.py
- src/fdk_rdf_parser/parse_functions/event.py
- tests/test_public_service.py
part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/837
> feat: rm dependency on event-graph for service-parse

- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
relates to https://github.com/Informasjonsforvaltning/behov/issues/967
> chore: remove unused fields no longer included in skos v2

- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
closes https://github.com/Informasjonsforvaltning/behov/issues/970
> feat: add skos:definition for concept

- src/fdk_rdf_parser/classes/concept.py
- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
> feat: add definisjon euvoc-XLnote

- .github/workflows/coverage.yml
- noxfile.py
- src/fdk_rdf_parser/classes/concept.py
- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/796
> feat: add support for multiple concept definitions

- src/fdk_rdf_parser/parse_functions/concept.py
- src/fdk_rdf_parser/rdf_utils/__init__.py
- src/fdk_rdf_parser/rdf_utils/utils.py
- tests/test_concept.py
> feat: add direct indication for labels

- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
> chore: update associative relation to skos v2

- src/fdk_rdf_parser/parse_functions/concept.py
- src/fdk_rdf_parser/parse_functions/temporal.py
- tests/test_concept.py
closes [#304](https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/304)
closes #299
> chore: update collection label according to skos v2

- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
> feat: support generic relations from skos v2

- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
> feat: support partitive relations from skos v2

- poetry.lock
- pyproject.toml
- src/fdk_rdf_parser/parse_functions/concept.py
- tests/test_concept.py
part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/993
> fix: correctly parse source text value for concept xlDefinition
